### ISSUE TITLE
Getting compile error while executing this project

### ISSUE THREAD

**Issue by himsoftware** [Wotzhs/react-redux-graphql-app#1]
Hi Wotzhs,
First thanks for sharing the code in gitub.
![image](https://user-images.githubusercontent.com/8951914/28202032-31845404-6891-11e7-8b91-359784707c2f.png)
and when I comments the line in src\index.js it run but output is like 
![image](https://user-images.githubusercontent.com/8951914/28202147-aef0d2f0-6891-11e7-9aeb-b506b40720e2.png)
Please look into this?
Regards,
Himanshu Pandey
+918411922005

**Comment by wotzhs** [comment]
Hi Himanshu,

Thank you for raising this, the vendor code was omitted from the repo earlier, i have now added them, you can do a `git pull` and run again.

Regards,
Sean
